version: '3.9'

services:
  php-env:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 8081:80
  
  mysql_db:
    image: mysql:latest
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 'root'
       MYSQL_DATABASE: 'db_smartplug'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'pass'


  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1